### ISSUE TITLE
Some of numbers in a square.

### ISSUE THREAD

**Issue by AlexNenartovich** [cthuff/CS149-Operating-Systems#1]
This probably doesn't matter any more since the class is over, but regarding your Sudoku program, just because the sum of numbers in a square is 45 does not mean the square is valid. Checking that the sum is 45 is not enough. Eg: 5,5,5,5,5,7,8,3,2   -> 9 numbers and the sum is 45 but the square is obviously not valid.

**Comment by cthuff** [comment]
Firstly, the statistical likelihood of every row, column, and square, all happening to add up to 45 would be highly unlikely to occur. That’s why I check the rows and columns in addition to checking the square. Secondly, I have comments in my code that should explain all of this to you.

**Comment by AlexNenartovich** [comment]
I've seen your code and comments, that's why I replied. Of course, the
statistical likelihood of this happening is very low but you still cannot
use it as an argument for a valid sudoku. Sum = 45 is a necessary but not a
sufficient condition.
Great job otherwise.
